globals:
  project_root: /root/bishe
  device: cuda:0
  shape: [512, 512]
  batch_size: 1
  latency_repeat: 300

  prune_defaults:
    mode: mlp_bottleneck
    importance: group_magnitude
    prune_stages: [2, 3, 4]
    iterative_steps: 8
    max_pruning_ratio: 1.00
    round_to: 40
    taylor_batches: 64

  finetune_defaults:
    epochs: 20
    lr: 3e-5
    weight_decay: 0.01

  models:
    b0:
      config: configs/railsem19/segformer_b0_rs19_512x512_150ep_rtx4090.py
      checkpoint: runs/B0_best_mIoU_v1.pth
      baseline_output_dir: output/segformer_b0_baseline

    b1:
      config: configs/railsem19/segformer_b1_rs19_512x512_100ep_rtx4090.py
      checkpoint: /root/bishe/runs/B1_best_mIoU.pth
      baseline_output_dir: output/segformer_b1_baseline
#########################################
experiments:
  b0_base:
    model: b0
    type: baseline

  b1_base:
    model: b1
    type: baseline

#######################################
  b0_p10:
    model: b0
    type: prune
    ratio: 0.10

  b0_p30:
    model: b0
    type: prune
    ratio: 0.30
    
  b0_p50:
    model: b0
    type: prune
    ratio: 0.50
    finetune_epochs: 25
######################################
  b1_p10:
    model: b1
    type: prune
    ratio: 0.10

  b1_p30:
    model: b1
    type: prune
    ratio: 0.30
  
  b1_p50:
    model: b1
    type: prune
    ratio: 0.50
    finetune_epochs: 30

  b1_p70:
    model: b1
    type: prune
    ratio: 0.70

  b1_p90:
    model: b1
    type: prune
    ratio: 0.90
    finetune_epochs: 60
    
#####################################
  b1_p30_global:
    model: b1
    type: prune
    ratio: 0.30
    global_pruning: true
    isomorphic: false

  b1_p30_global_iso:
    model: b1
    type: prune
    ratio: 0.30
    global_pruning: true
    isomorphic: true
###################################
  b1_p50_global:
    model: b1
    type: prune
    ratio: 0.50
    global_pruning: true
    isomorphic: false

  b1_p50_global_iso:
    model: b1
    type: prune
    ratio: 0.50
    global_pruning: true
    isomorphic: true

  b1_p90_global:
    model: b1
    type: prune
    ratio: 0.90
    global_pruning: true
    isomorphic: false
    finetune_epochs: 60

  b1_p90_global_iso:
    model: b1
    type: prune
    ratio: 0.90
    global_pruning: true
    isomorphic: true
    finetune_epochs: 60

###################### A:uniform pruning + global pruning #####################
  b1_uni_p30_global:
    model: b1
    type: prune
    mode: uniform_linear
    ratio: 0.30
    global_pruning: true
    isomorphic: false
    finetune_epochs: 20

  b1_uni_p30_global_iso:
    model: b1
    type: prune
    mode: uniform_linear
    ratio: 0.30
    global_pruning: true
    isomorphic: true
    finetune_epochs: 20

  b1_uni_p50_global:
    model: b1
    type: prune
    mode: uniform_linear
    ratio: 0.50
    global_pruning: true
    isomorphic: false
    finetune_epochs: 20

  b1_uni_p50_global_iso:
    model: b1
    type: prune
    mode: uniform_linear
    ratio: 0.50
    global_pruning: true
    isomorphic: true
    finetune_epochs: 100

  b1_uni_p70_global:
    model: b1
    type: prune
    mode: uniform_linear
    ratio: 0.70
    global_pruning: true
    isomorphic: false
    finetune_epochs: 60

  b1_uni_p70_global_iso:
    model: b1
    type: prune
    mode: uniform_linear
    ratio: 0.70
    global_pruning: true
    isomorphic: true
    finetune_epochs: 60

  b1_uni_p90_global:
    model: b1
    type: prune
    mode: uniform_linear
    ratio: 0.90
    global_pruning: true
    isomorphic: false
    finetune_epochs: 60

  b1_uni_p90_global_iso:
    model: b1
    type: prune
    mode: uniform_linear
    ratio: 0.90
    global_pruning: true
    isomorphic: true
    finetune_epochs: 60

######################mlp_bottleneck + global pruning [1,2,3,4] ############
  b1_mlp_all_p50_global:
    model: b1
    type: prune
    mode: mlp_bottleneck
    prune_stages: [1, 2, 3, 4]
    ratio: 0.50
    global_pruning: true
    isomorphic: false
    finetune_epochs: 45

  b1_mlp_all_p50_global_iso:
    model: b1
    type: prune
    mode: mlp_bottleneck
    prune_stages: [1, 2, 3, 4]
    ratio: 0.50
    global_pruning: true
    isomorphic: true
    finetune_epochs: 45

  b1_mlp_all_p70_global:
    model: b1
    type: prune
    mode: mlp_bottleneck
    prune_stages: [1, 2, 3, 4]
    ratio: 0.70
    global_pruning: true
    isomorphic: false
    finetune_epochs: 60

  b1_mlp_all_p70_global_iso:
    model: b1
    type: prune
    mode: mlp_bottleneck
    prune_stages: [1, 2, 3, 4]
    ratio: 0.70
    global_pruning: true
    isomorphic: true
    finetune_epochs: 60


######################uniform pruning + global pruning [1,2,3,4] ############
  b1_uni_all_p30_global:
    model: b1
    type: prune
    mode: uniform_linear
    prune_stages: [1, 2, 3, 4]
    ratio: 0.30
    global_pruning: true
    isomorphic: false
    finetune_epochs: 45

  b1_uni_all_p30_global_iso:
    model: b1
    type: prune
    mode: uniform_linear
    prune_stages: [1, 2, 3, 4]
    ratio: 0.30
    global_pruning: true
    isomorphic: true
    finetune_epochs: 45

  b1_uni_all_p50_global:
    model: b1
    type: prune
    mode: uniform_linear
    prune_stages: [1, 2, 3, 4]
    ratio: 0.50
    global_pruning: true
    isomorphic: false
    finetune_epochs: 60

  b1_uni_all_p50_global_iso:
    model: b1
    type: prune
    mode: uniform_linear
    prune_stages: [1, 2, 3, 4]
    ratio: 0.50
    global_pruning: true
    isomorphic: true
    finetune_epochs: 60

##################### taylor importance #####################
  b1_p30_taylor:
    model: b1
    type: prune
    ratio: 0.30
    importance: taylor
    taylor_batches: 64
    

######################## taylor importance + global pruning #####################
  b1_p30_taylor_global:
    model: b1
    type: prune
    ratio: 0.30
    importance: taylor
    taylor_batches: 64
    global_pruning: true
    isomorphic: false

  b1_p30_taylor_global_iso:
    model: b1
    type: prune
    ratio: 0.30
    importance: taylor
    taylor_batches: 64
    global_pruning: true
    isomorphic: true
